"""Self-play training data: the universe learns from its own games and its own
deeper search.

chess:  two engines built on the SAME physical constants play each other over a
        time budget; the "explorer" adds exploration noise (random posterior
        seeds on the tie-break head) so games spread across the move tree.
        Every few plies the position is sampled:
          * OUTCOME example — the final game result (real, not invented).
          * POLICY example  — all legal child moves + a "teacher" verdict: the
            SAME gravity kernel with a bigger time budget says which move is
            best. The teacher is never told a chess rule; it is just the
            universe looked at more deeply. This is self-teaching, the
            supervised analogue of bootstrapping a deeper orbit from a shallow
            one — no external data, no books, no hardcoded concepts.
physics: supervision is entirely generated by the system's own dynamics. The
        labels are real outcomes and the kernel's own deeper integrations;
        gradient descent then reshapes the physical constants so the shallow
        field reads like the deep field.
"""

from __future__ import annotations

import numpy as np

import chess

from ..core.fastboard import FastBoard
from ..core.constants import Constants
from ..core.transitions import child_mass_vector
from . import data as _data


def play_training_games(constants: Constants,
                        *,
                        games: int = 8,
                        max_plies: int = 48,
                        move_ms: float = 250.0,
                        teacher_ms: float = 750.0,
                        sample_every: int = 3,
                        min_ply: int = 4,
                        max_children: int = 64,
                        seed: int = 0,
                        verbose: bool = False):
    """Play `games` self-play games and harvest training examples.

    Returns (examples, summary) where examples are dicts in the layout of
    training/data.py (to_arrays consumes them) and summary holds outcome
    statistics (decisive/draw counts, positions sampled).
    """
    from .. import RocheEngine
    from ..search.minimax import iterative_search

    rng = np.random.default_rng(seed)
    explorer = RocheEngine(constants)   # explorer: multiverse tie-break w/ random seed
    teacher = RocheEngine(constants)    # teacher: same kernel, bigger time budget

    def _board_to_examples(board: chess.Board, mv_played_by_teacher=None):
        """Build one example dict from a python-chess board (teacher-labeled)."""
        fb = FastBoard.from_chess(board)
        parent, child_m, mask, legal = _data._children(board)
        # teacher verdict from the DEEPER budget — the expert move to imitate
        tmv = teacher.play(board, search_time_ms=teacher_ms,
                           use_multiverse=True, multiverse_seed=int(rng.integers(2**31)))
        if tmv is None:
            return None
        expert_tup = (tmv.from_square, tmv.to_square, tmv.promotion or 0)
        try:
            eidx = legal.index(expert_tup)
        except ValueError:
            return None
        if eidx >= max_children:
            return None
        is_cap = 1.0 if board.is_capture(tmv) else 0.0
        return {
            "mass": parent,
            "outcome": 0.0,  # patched with the game result later
            "turn": 0.0 if board.turn == chess.WHITE else 1.0,
            "child_m": child_m,
            "mask": mask,
            "expert_idx": int(eidx),
            "expert_cap": is_cap,
        }

    examples = []
    wins = losses = draws = 0
    for g in range(games):
        board = chess.Board()
        game_examples = []
        plies = 0
        while not board.is_game_over() and plies < max_plies:
            # ── sample: label the position BEFORE this ply's move is played
            if plies >= min_ply and plies % sample_every == 0:
                ex = _board_to_examples(board)
                if ex is not None:
                    game_examples.append(ex)
            # ── play: the explorer picks with a noisy posterior seed (spread
            # across near-tie candidates); the teacher's verdict is the label
            mv = explorer.play(board, search_time_ms=move_ms,
                               use_multiverse=True,
                               multiverse_seed=int(rng.integers(2**31)))
            if mv is None:
                break
            board.push(mv)
            plies += 1
        oc = board.outcome()
        if oc is None or oc.winner is None:
            outcome, draws = 0.0, draws + 1
        elif oc.winner == chess.WHITE:
            outcome, wins = 1.0, wins + 1
        else:
            outcome, losses = -1.0, losses + 1
        # real outcome label for every sampled position of this game
        for ex in game_examples:
            ex["outcome"] = outcome
        examples.extend(game_examples)
        if verbose:
            print(f"[selfplay] game {g + 1}/{games}: {plies} plies, "
                  f"{'1-0' if outcome > 0 else '0-1' if outcome < 0 else 'draw'}, "
                  f"{len(game_examples)} examples")

    summary = {
        "games": games, "wins": wins, "losses": losses, "draws": draws,
        "examples": len(examples),
    }
    return examples, summary
