"""Self-play training data: the universe learns from its own games and its own
deeper search.

chess:  two engines built on the SAME physical constants play each other over a
        time budget; the "explorer" adds exploration noise (random posterior
        seeds on the tie-break head) so games spread across the move tree.
        Every few plies the position is sampled:
          * OUTCOME example — the final game result (real, not invented).
          * POLICY example  — all legal child moves + a "teacher" verdict: the
            SAME gravity kernel with a bigger time budget says which move is
            best. The teacher is never told a chess rule; it is just the
            universe looked at more deeply. This is self-teaching, the
            supervised analogue of bootstrapping a deeper orbit from a shallow
            one — no external data, no books, no hardcoded concepts.
physics: supervision is entirely generated by the system's own dynamics. The
        labels are real outcomes and the kernel's own deeper integrations;
        gradient descent then reshapes the physical constants so the shallow
        field reads like the deep field.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

import chess

from ..core.fastboard import FastBoard
from ..core.constants import Constants
from ..core.transitions import child_mass_vector
from . import data as _data


def play_training_games(constants: Constants,
                        *,
                        games: int = 8,
                        max_plies: int = 48,
                        move_ms: float = 250.0,
                        teacher_ms: float = 750.0,
                        sample_every: int = 3,
                        min_ply: int = 4,
                        max_children: int = 64,
                        seed: int = 0,
                        verbose: bool = False,
                        teacher_engine: str | None = None,
                        teacher_elo: int = 1600):
    """Play `games` self-play games and harvest training examples.

    Returns (examples, summary) where examples are dicts in the layout of
    training/data.py (to_arrays consumes them) and summary holds outcome
    statistics (decisive/draw counts, positions sampled).
    """
    import shutil
    import chess.engine
    from .. import RocheEngine
    from ..search.minimax import iterative_search

    rng = np.random.default_rng(seed)
    explorer = RocheEngine(constants)   # explorer: multiverse tie-break w/ random seed
    teacher = RocheEngine(constants)    # fallback teacher: same kernel, bigger time budget

    external_teacher = None
    if teacher_engine:
        bin_path = teacher_engine if Path(teacher_engine).is_file() else shutil.which(teacher_engine)
        if not bin_path and teacher_engine == "stockfish":
            for candidate in ["/usr/games/stockfish", "/usr/local/bin/stockfish", "/usr/bin/stockfish"]:
                if Path(candidate).is_file():
                    bin_path = candidate
                    break
        if bin_path:
            try:
                external_teacher = chess.engine.SimpleEngine.popen_uci(bin_path)
                try:
                    external_teacher.configure({"UCI_LimitStrength": True, "UCI_Elo": int(teacher_elo)})
                except Exception:
                    pass
                if verbose:
                    print(f"[selfplay] using external master teacher: {bin_path} (calibrated Elo {teacher_elo})", flush=True)
            except Exception as e:
                if verbose:
                    print(f"[selfplay] warning: failed to launch external teacher '{teacher_engine}': {e}. Falling back to internal teacher.", flush=True)
                external_teacher = None
        else:
            if verbose:
                print(f"[selfplay] warning: external teacher '{teacher_engine}' not found on PATH. Falling back to internal teacher.", flush=True)

    def _board_to_examples(board: chess.Board, g: int = 0):
        """Build one example dict from a python-chess board (teacher-labeled)."""
        fb = FastBoard.from_chess(board)
        parent, child_m, mask, legal = _data._children(board)
        # teacher verdict: external master (e.g. Stockfish 1600) or deeper internal search
        if external_teacher is not None:
            try:
                limit = chess.engine.Limit(time=max(0.02, teacher_ms / 1000.0))
                tmv = external_teacher.play(board, limit).move
            except Exception:
                tmv = None
        else:
            tmv = teacher.play(board, search_time_ms=teacher_ms,
                               use_multiverse=True, multiverse_seed=int(rng.integers(2**31)))
        if tmv is None:
            return None
        expert_tup = (tmv.from_square, tmv.to_square, tmv.promotion or 0)
        try:
            eidx = legal.index(expert_tup)
        except ValueError:
            return None
        if eidx >= max_children:
            return None
        is_cap = 1.0 if board.is_capture(tmv) else 0.0
        return {
            "game_idx": int(g),
            "mass": parent,
            "outcome": 0.0,  # patched with the game result later
            "turn": 0.0 if board.turn == chess.WHITE else 1.0,
            "child_m": child_m,
            "mask": mask,
            "expert_idx": int(eidx),
            "expert_cap": is_cap,
        }

    examples = []
    wins = losses = draws = 0
    try:
        for g in range(games):
            board = chess.Board()
            game_examples = []
            plies = 0
            while not board.is_game_over() and plies < max_plies:
                # ── sample: label the position BEFORE this ply's move is played
                if plies >= min_ply and plies % sample_every == 0:
                    ex = _board_to_examples(board, g)
                    if ex is not None:
                        game_examples.append(ex)
                # ── play: the explorer picks with a noisy posterior seed (spread
                # across near-tie candidates); the teacher's verdict is the label
                mv = explorer.play(board, search_time_ms=move_ms,
                                   use_multiverse=True,
                                   multiverse_seed=int(rng.integers(2**31)))
                if mv is None:
                    break
                board.push(mv)
                plies += 1

            oc = board.outcome()
            truncated = (plies >= max_plies and (oc is None or oc.winner is None))
            if oc is not None and oc.winner is not None:
                outcome = 1.0 if oc.winner == chess.WHITE else -1.0
            elif truncated:
                outcome = _terminal_mass_edge(board)
            else:
                outcome = 0.0
            if outcome > 0:
                wins += 1
            elif outcome < 0:
                losses += 1
            else:
                draws += 1
            # real outcome label for every sampled position of this game
            for ex in game_examples:
                ex["outcome"] = outcome
            examples.extend(game_examples)
            if verbose:
                tag = "1-0" if outcome > 0 else "0-1" if outcome < 0 else "draw"
                if truncated:
                    tag += "#"
                print(f"[selfplay] game {g + 1}/{games}: {plies} plies, {tag}, "
                      f"{len(game_examples)} examples")
    finally:
        if external_teacher is not None:
            try:
                external_teacher.quit()
            except Exception:
                pass

    summary = {
        "games": games, "wins": wins, "losses": losses, "draws": draws,
        "examples": len(examples),
    }
    return examples, summary


def _terminal_mass_edge(board: chess.Board) -> float:
    """Signed army-mass difference at the terminal board (white - black), in
    the engine's own piece-mass units, thresholded into a +/-1 decision.

    Kings are excluded (both weigh 1000 and cancel), mirroring evaluate.py's
    army split. A clear mass edge = decisive; near-equal stays a draw.
    """
    import numpy as _np
    fb = FastBoard.from_chess(board)
    m = _np.asarray(fb.mass_vector(), dtype=_np.float32)
    abs_m = _np.abs(m)
    white = _np.where(m > 0, abs_m, 0.0)
    black = _np.where(m < 0, abs_m, 0.0)
    # exclude the supermassive kings
    white[int(_np.argmax((_np.abs(m) >= 500.0) & (m > 0)))] = 0.0
    black[int(_np.argmax((_np.abs(m) >= 500.0) & (m < 0)))] = 0.0
    diff = float(white.sum() - black.sum())
    # a full pawn (mass 1.0) of clear material at the horizon decides it
    if diff >= 1.0:
        return 1.0
    if diff <= -1.0:
        return -1.0
    return 0.0
